import UgpLean.ElegantKernel.Unconditional.UCLCalibration
import UgpLean.ElegantKernel.Unconditional.UCLMassOrderingSBounds

namespace UgpLean.ElegantKernel.Unconditional.UCLMassOrderingDelta

open Real
open UgpLean.ElegantKernel.Unconditional.UCLCalibration
open UgpLean.ElegantKernel.Unconditional.UCLMassOrderingSBounds

export UCLMassOrderingSBounds (lepton_log_delta12 lepton_log_delta23 up_log_delta12 up_log_delta23 down_log_delta12 down_log_delta23)

end UgpLean.ElegantKernel.Unconditional.UCLMassOrderingDelta
