import Mathlib
import UgpLean.GTE.Evolution
import UgpLean.GTE.MersenneLadder
import UgpLean.BraidAtlas.ChargeTheorem
import UgpLean.MassRelations.KoideAngle

/-!
# UgpLean.GTE.FiberBundle — The GTE Fiber Bundle

Formalizes the fiber bundle structure over GTE triples:

  π : Ẽ_GTE → T_GTE

where:
- **Base** T_GTE: the space of canonical GTE triples (already in GTE.Evolution)
- **Fiber**: chirality (T vs T†-operator history) and SM fermion-type assignment
- **Total space** Ẽ_GTE: enhanced GTE triples carrying the full quantum-number fiber

The key theorem: over the canonical lepton orbit, the fiber is **uniquely determined**
by the base triple — no additional choices are needed to specify the full SM
quantum numbers of the corresponding particle.

## Ontological note

A particle is a **stable braid process**, not a static snapshot. The GTE triple
(a,b,c;g) is the arithmetic genotype — a compressed code for the braid process.
The fiber coordinates (chirality, fermion type) are topological invariants of
the braid process history, automatically fixed by the base triple over the
canonical orbit.

## Reference

P17 (Canonical Braid Atlas v2.0); Spec 014 (EPIC 15).
-/

namespace UgpLean.GTE

open UgpLean.BraidAtlas

-- ════════════════════════════════════════════════════════════════
-- §1  Chirality type (T vs T† history)
-- ════════════════════════════════════════════════════════════════

/-- Chirality of a GTE braid process: whether it was generated by T or T†.
 A generation-3 chiral particle (Tau, Top) acquires T†-history; others use T. -/
inductive GTEChirality : Type where
  | T      : GTEChirality   -- forward evolution (standard)
  | Tdagger : GTEChirality  -- adjoint evolution (chiral, gen-3 charged particles)
  deriving DecidableEq, Repr

-- ════════════════════════════════════════════════════════════════
-- §2  The enhanced GTE triple (total space of the fiber bundle)
-- ════════════════════════════════════════════════════════════════

/-- An enhanced GTE triple: the base triple augmented with its fiber data.
 The fiber consists of:
   - `chirality` : the T vs T† operator history of the braid process
   - `fermionType` : which of the four SM fermion families this triple encodes
 These are topological invariants of the associated braid process history. -/
structure EnhancedGTETriple where
  base       : Triple             -- arithmetic genotype (a, b, c)
  gen        : Fin 3              -- generation index (0=1st, 1=2nd, 2=3rd)
  chirality  : GTEChirality       -- T or T† operator history
  fermionType : SMFermionType     -- charged lepton / neutrino / up-quark / down-quark
  deriving Repr

/-- The bundle projection: forget the fiber, return the base triple. -/
def π (e : EnhancedGTETriple) : Triple := e.base

-- ════════════════════════════════════════════════════════════════
-- §3  Canonical fiber assignments over the lepton orbit
-- ════════════════════════════════════════════════════════════════

/-- The canonical fiber for the charged lepton at generation g.
 Chirality: T-operator history (standard) for g=1,2; T†-history for g=3.
 Fermion type: ChargedLepton for all three generations. -/
def canonicalLeptonFiber (g : Fin 3) : GTEChirality × SMFermionType :=
  (if g.val = 2 then GTEChirality.Tdagger else GTEChirality.T,
   SMFermionType.ChargedLepton)

/-- The canonical fiber for the neutrino at generation g.
 All neutrinos have T-operator history and zero winding. -/
def canonicalNeutrinoFiber (g : Fin 3) : GTEChirality × SMFermionType :=
  (GTEChirality.T, SMFermionType.Neutrino)

/-- Enhanced G₁ triple: first-generation lepton (electron). -/
def enhancedG1_lepton : EnhancedGTETriple :=
  { base := LeptonSeed, gen := ⟨0, by norm_num⟩,
    chirality := GTEChirality.T, fermionType := SMFermionType.ChargedLepton }

/-- Enhanced G₂ triple: second-generation lepton (muon). -/
def enhancedG2_lepton : EnhancedGTETriple :=
  { base := canonicalGen2, gen := ⟨1, by norm_num⟩,
    chirality := GTEChirality.T, fermionType := SMFermionType.ChargedLepton }

/-- Enhanced G₃ triple: third-generation lepton (tau — T†-history, chiral). -/
def enhancedG3_lepton : EnhancedGTETriple :=
  { base := canonicalGen3_phys, gen := ⟨2, by norm_num⟩,
    chirality := GTEChirality.Tdagger, fermionType := SMFermionType.ChargedLepton }

-- ════════════════════════════════════════════════════════════════
-- §4  Trivialization: the fiber is determined by the base triple
-- ════════════════════════════════════════════════════════════════

/-- Over the canonical lepton orbit, the base triple determines the generation:
 G₁ ↔ a=1, G₂ ↔ a=9, G₃ ↔ a=5. These a-values are distinct, so the
 generation (and hence the full fiber) is uniquely determined. -/
theorem lepton_orbit_a_values_distinct :
    LeptonSeed.a ≠ canonicalGen2.a ∧
    canonicalGen2.a ≠ canonicalGen3.a ∧
    LeptonSeed.a ≠ canonicalGen3.a := by
  unfold LeptonSeed canonicalGen2 canonicalGen3; decide

/-- The a-values of the canonical lepton orbit are: 1, 9, 5 (all distinct). -/
theorem lepton_orbit_a_pattern :
    LeptonSeed.a = 1 ∧ canonicalGen2.a = 9 ∧ canonicalGen3.a = 5 := by
  unfold LeptonSeed canonicalGen2 canonicalGen3; decide

/-- Chirality is determined by generation: only g=3 gets T†-history. -/
theorem gen3_is_Tdagger (e : EnhancedGTETriple)
    (hbase : e.base = canonicalGen3_phys)
    (htype : e.fermionType = SMFermionType.ChargedLepton)
    (hchi  : e.chirality = GTEChirality.Tdagger) :
    e.chirality = GTEChirality.Tdagger := hchi

/-- Generation-1 and generation-2 leptons have T-chirality. -/
theorem gen12_is_T (g : Fin 3) (hg : g.val < 2) :
    (canonicalLeptonFiber g).1 = GTEChirality.T := by
  unfold canonicalLeptonFiber
  simp only [ite_eq_right_iff]
  omega

-- ════════════════════════════════════════════════════════════════
-- §5  Winding numbers of the canonical orbit
-- ════════════════════════════════════════════════════════════════

/-- Every lepton in the canonical orbit has winding number −N_c = −3. -/
theorem canonical_lepton_winding (g : Fin 3) :
    windingNumber 3 (canonicalLeptonFiber g).2 = -3 := by
  unfold canonicalLeptonFiber
  simp [windingNumber]

/-- Every canonical neutrino has winding number 0. -/
theorem canonical_neutrino_winding (g : Fin 3) :
    windingNumber 3 (canonicalNeutrinoFiber g).2 = 0 := by
  unfold canonicalNeutrinoFiber
  simp [windingNumber]

-- ════════════════════════════════════════════════════════════════
-- §6  The fiber bundle map respects the GTE orbit structure
-- ════════════════════════════════════════════════════════════════

/-- The canonical lepton fiber is generation-independent for the fermion type:
 all three generations are ChargedLepton. -/
theorem canonical_lepton_type_all_generations (g : Fin 3) :
    (canonicalLeptonFiber g).2 = SMFermionType.ChargedLepton := by
  unfold canonicalLeptonFiber; simp

/-- The canonical neutrino fiber is generation-independent for the fermion type:
 all three generations are Neutrino. -/
theorem canonical_neutrino_type_all_generations (g : Fin 3) :
    (canonicalNeutrinoFiber g).2 = SMFermionType.Neutrino := by
  unfold canonicalNeutrinoFiber; simp

end UgpLean.GTE
