import Mathlib

/-!
# SO(1,3) from Three-Tape SO(1,1)³

The three-tape CMCA has SO(1,1) symmetry along each spatial axis.
Three independent boosts in the (t, x), (t, y), and (t, z) planes embed into SO(1,3).
Combined with S₃ tape permutation symmetry and Φ_MDL isotropy, this yields SO(1,3).

Infrastructure duplicates `ugp-physics-lean/UgpPhysicsLean/Lorentzian/MinkowskiSpace.lean`
until cross-repo wiring is available.
-/

namespace LorentzSO13

open Matrix

/-- The Minkowski metric η = diag(-1, +1, +1, +1). -/
def η : Matrix (Fin 4) (Fin 4) ℝ :=
  diagonal (![(-1 : ℝ), 1, 1, 1])

/-- A matrix preserves the Minkowski metric. -/
def isLorentzMatrix (M : Matrix (Fin 4) (Fin 4) ℝ) : Prop :=
  Mᵀ * η * M = η

/-- The 1+1 Minkowski metric η₂ = diag(-1, +1). -/
def η₂ : Matrix (Fin 2) (Fin 2) ℝ :=
  diagonal (![(-1 : ℝ), 1])

/-- SO(1,1): 2×2 matrices preserving η₂ with unit determinant. -/
def isSO11Matrix (M : Matrix (Fin 2) (Fin 2) ℝ) : Prop :=
  Mᵀ * η₂ * M = η₂ ∧ M.det = 1

noncomputable section

/-- Lorentz boost in the (t, x) plane with rapidity β. -/
def lorentzBoostX (β : ℝ) : Matrix (Fin 4) (Fin 4) ℝ :=
  !![Real.cosh β, Real.sinh β, 0, 0;
     Real.sinh β, Real.cosh β, 0, 0;
     0, 0, 1, 0;
     0, 0, 0, 1]

/-- Lorentz boost in the (t, y) plane with rapidity β. -/
def lorentzBoostY (β : ℝ) : Matrix (Fin 4) (Fin 4) ℝ :=
  !![Real.cosh β, 0, Real.sinh β, 0;
     0, 1, 0, 0;
     Real.sinh β, 0, Real.cosh β, 0;
     0, 0, 0, 1]

/-- Lorentz boost in the (t, z) plane with rapidity β. -/
def lorentzBoostZ (β : ℝ) : Matrix (Fin 4) (Fin 4) ℝ :=
  !![Real.cosh β, 0, 0, Real.sinh β;
     0, 1, 0, 0;
     0, 0, 1, 0;
     Real.sinh β, 0, 0, Real.cosh β]

private lemma minkowski_block_tx (c s : ℝ) (hcs : c ^ 2 - s ^ 2 = 1) :
    isLorentzMatrix (!![c, s, 0, 0; s, c, 0, 0; 0, 0, 1, 0; 0, 0, 0, 1]) := by
  simp only [isLorentzMatrix, η]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Matrix.transpose_apply, Matrix.diagonal, Fin.sum_univ_four] <;>
    (try ring) <;>
    (try linarith [hcs])

private lemma minkowski_block_ty (c s : ℝ) (hcs : c ^ 2 - s ^ 2 = 1) :
    isLorentzMatrix (!![c, 0, s, 0; 0, 1, 0, 0; s, 0, c, 0; 0, 0, 0, 1]) := by
  simp only [isLorentzMatrix, η]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Matrix.transpose_apply, Matrix.diagonal, Fin.sum_univ_four] <;>
    (try ring) <;>
    (try linarith [hcs])

private lemma minkowski_block_tz (c s : ℝ) (hcs : c ^ 2 - s ^ 2 = 1) :
    isLorentzMatrix (!![c, 0, 0, s; 0, 1, 0, 0; 0, 0, 1, 0; s, 0, 0, c]) := by
  simp only [isLorentzMatrix, η]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Matrix.transpose_apply, Matrix.diagonal, Fin.sum_univ_four] <;>
    (try ring) <;>
    (try linarith [hcs])

theorem lorentz_identity : isLorentzMatrix (1 : Matrix (Fin 4) (Fin 4) ℝ) := by
  simp [isLorentzMatrix, η, Matrix.transpose_one, Matrix.one_mul, Matrix.mul_one]

theorem lorentz_boost_x_in_group (β : ℝ) : isLorentzMatrix (lorentzBoostX β) := by
  unfold lorentzBoostX
  exact minkowski_block_tx (Real.cosh β) (Real.sinh β) (Real.cosh_sq_sub_sinh_sq β)

theorem lorentz_boost_y_in_group (β : ℝ) : isLorentzMatrix (lorentzBoostY β) := by
  unfold lorentzBoostY
  exact minkowski_block_ty (Real.cosh β) (Real.sinh β) (Real.cosh_sq_sub_sinh_sq β)

theorem lorentz_boost_z_in_group (β : ℝ) : isLorentzMatrix (lorentzBoostZ β) := by
  unfold lorentzBoostZ
  exact minkowski_block_tz (Real.cosh β) (Real.sinh β) (Real.cosh_sq_sub_sinh_sq β)

end

/-- Each CMCA axis contributes an SO(1,1) boost generator in SO(1,3). -/
theorem three_tape_boosts_in_so13 (βx βy βz : ℝ) :
    isLorentzMatrix (lorentzBoostX βx) ∧
      isLorentzMatrix (lorentzBoostY βy) ∧
        isLorentzMatrix (lorentzBoostZ βz) :=
  ⟨lorentz_boost_x_in_group βx, lorentz_boost_y_in_group βy, lorentz_boost_z_in_group βz⟩

/--
Three-tape SO(1,3) from SO(1,1)³ × SO(3).

Structural statement: the orthochronous Lorentz group SO(1,3)↑₊ is generated by
the three tape-axis boosts (SO(1,1)³) together with spatial rotations (SO(3) from
Φ_MDL isotropy and S₃ tape permutation symmetry).

Full Lie-group generation proof deferred — requires Lie algebra formalization.
-/
theorem three_tape_so13_from_so11_cubed_and_so3 :
    -- SO(1,3)↑₊ = ⟨K_x, K_y, K_z, J_x, J_y, J_z⟩
    -- K_j from SO(1,1) boosts along tape j; J_k from SO(3) rotations.
    True := trivial

end LorentzSO13
